import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from "next/router"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { locale } = useRouter();
	const defaultLang = locale === 'es'

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <main>
          <div className='mt-12'>
            <h2 className='text-3xl text-center text-red-400'>
              { defaultLang ? 'En Construcción' : 'Under Construction' }
            </h2>
          </div>
        </main>
    </>
  )
}
